#pragma once

#include <stdint.h>

typedef int8_t FxI8;
typedef int16_t FxI16;
typedef int32_t FxI32;
typedef int64_t FxI64;
typedef uint8_t FxU8;
typedef uint16_t FxU16;
typedef uint32_t FxU32;
typedef uint64_t FxU64;
typedef uintptr_t AnyPtr;
typedef int32_t FxBool;
typedef float FxFloat;
typedef double FxDouble;

constexpr FxBool FXTRUE = 1;
constexpr FxBool FXFALSE = 0;

#define FXBIT(i) (1 << (i))
#define G3_ASPECT_TRANSLATE(_aspect) (0x03 - _aspect)

constexpr FxI32 GLIDE_NUM_TMU = 2;
constexpr FxI32 GLIDE_MAX_TMU = 4;
constexpr FxU32 GLIDE_NO_TEXTURE = 0xFFFFFFFF;
constexpr FxI32 GLIDE_MAX_TEXTURESTAGES = 3;
constexpr FxI32 GLIDE_MAX_VERTEX_PARAM_COUNT = 14;
constexpr FxI32 MAX_NUM_SST = 4;
constexpr FxI32 MAX_NUM_CONTEXTS = 16;
constexpr FxI32 GLIDE_MAX_AUX_BUFFERS = 1;
constexpr FxI32 GLIDE_MAX_SWAP_CHAIN_BUFFERS = 3;
constexpr FxI32 GLIDE_MIN_SWAP_CHAIN_BUFFERS = 2;
constexpr FxI32 VOODOO_GAMMA_TABLE_SIZE = 256;
constexpr FxU32 VOODOO_PALETTE_TABLE_SIZE = 256u;
constexpr FxU32 VOODOO_NCC_TABLE_SIZE = 112u;
constexpr FxI32 SST1_BITS_DEPTH = 16;
constexpr FxI32 SST1_ZDEPTHVALUE_NEAREST = 0xFFFF;
constexpr FxI32 SST1_ZDEPTHVALUE_FARTHEST = 0x0000;
constexpr FxI32 SST1_WDEPTHVALUE_NEAREST = 0x0000;
constexpr FxI32 SST1_WDEPTHVALUE_FARTHEST = 0xFFFF;
constexpr FxI32 SST1_TEXTURE_ALIGN = 0x08;
constexpr FxI32 SST1_TEXTURE_ALIGN_MASK = SST1_TEXTURE_ALIGN - 0x01;
constexpr FxI32 GAMMA_TABLE_ENTRIES_COUNT = 256;
constexpr FxI32 FOG_TABLE_ENTRIES_COUNT = 64;
constexpr FxI32 NAPALM_ZDEPTHVALUE_NEAREST = 0xFFFFFF;
constexpr FxI32 NAPALM_WDEPTHVALUE_FARTHEST = 0xFFFFFF;
constexpr float GLIDE_FPBIAS = 786432.875;

typedef void (*GrErrorCallbackFnc_t)(const char *string, FxBool fatal);

typedef FxU32 GrColor_t;
typedef FxU8  GrAlpha_t;
typedef FxU32 GrMipMapId_t;
typedef FxU8  GrFog_t;
typedef unsigned long GrContext_t;
typedef int (__stdcall *GrProc)();

constexpr FxFloat GR_LODBIAS_BILINEAR = 0.5f;
constexpr FxFloat GR_LODBIAS_TRILINEAR = 0.0f;

enum GrChipID_t : FxI32 {
  GR_TMU0 = 0x00,
  GR_TMU1 = 0x01,
  GR_TMU2 = 0x02,
  GR_TMU3 = 0x03,
};

constexpr FxI32 GR_FBI = 0x00;

enum GrCombineFunction_t : FxI32 {
  GR_COMBINE_FUNCTION_ZERO = 0x00,
  GR_COMBINE_FUNCTION_NONE = GR_COMBINE_FUNCTION_ZERO,
  GR_COMBINE_FUNCTION_LOCAL = 0x01,
  GR_COMBINE_FUNCTION_LOCAL_ALPHA = 0x02,
  GR_COMBINE_FUNCTION_SCALE_OTHER = 0x03,
  GR_COMBINE_FUNCTION_BLEND_OTHER = GR_COMBINE_FUNCTION_SCALE_OTHER,
  GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL = 0x04,
  GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA = 0x05,
  GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL = 0x06,
  GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL = 0x07,
  GR_COMBINE_FUNCTION_BLEND = GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL,
  GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA = 0x08,
  GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL = 0x09,
  GR_COMBINE_FUNCTION_BLEND_LOCAL = GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL,
  // Yes, bizarrely there is a 0x0A-0x0F hole, someone back in time couldn't count in hex?
  GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA = 0x10,
};

enum GrCombineFactor_t : FxI32 {
  GR_COMBINE_FACTOR_ZERO = 0x00,
  GR_COMBINE_FACTOR_NONE = GR_COMBINE_FACTOR_ZERO,
  GR_COMBINE_FACTOR_LOCAL = 0x01,
  GR_COMBINE_FACTOR_OTHER_ALPHA = 0x02,
  GR_COMBINE_FACTOR_LOCAL_ALPHA = 0x03,
  GR_COMBINE_FACTOR_TEXTURE_ALPHA = 0x04,
  GR_COMBINE_FACTOR_DETAIL_FACTOR = GR_COMBINE_FACTOR_TEXTURE_ALPHA,
  GR_COMBINE_FACTOR_TEXTURE_RGB = 0x05,
  GR_COMBINE_FACTOR_LOD_FRACTION = 0x05,
  GR_COMBINE_FACTOR_ONE = 0x08,
  GR_COMBINE_FACTOR_ONE_MINUS_LOCAL = 0x09,
  GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA = 0x0A,
  GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA = 0x0B,
  GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA = 0x0C,
  GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR = GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA,
  GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION = 0x0D,
};

enum GrCombineLocal_t : FxI32 {
  GR_COMBINE_LOCAL_ITERATED = 0x00,
  GR_COMBINE_LOCAL_CONSTANT = 0x01,
  GR_COMBINE_LOCAL_NONE = GR_COMBINE_LOCAL_CONSTANT,
  GR_COMBINE_LOCAL_DEPTH = 0x02,
};

enum GrCombineOther_t : FxI32 {
  GR_COMBINE_OTHER_ITERATED = 0x00,
  GR_COMBINE_OTHER_TEXTURE = 0x01,
  GR_COMBINE_OTHER_CONSTANT = 0x02,
  GR_COMBINE_OTHER_NONE = GR_COMBINE_OTHER_CONSTANT,
};

enum GrAlphaSource_t : FxI32 {
  GR_ALPHASOURCE_CC_ALPHA = 0x00,
  GR_ALPHASOURCE_ITERATED_ALPHA = 0x01,
  GR_ALPHASOURCE_TEXTURE_ALPHA = 0x02,
  GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA = 0x03,
};

enum GrColorCombineFnc_t : FxI32 {
  GR_COLORCOMBINE_ZERO = 0x00,
  GR_COLORCOMBINE_CCRGB = 0x01,
  GR_COLORCOMBINE_ITRGB = 0x02,
  GR_COLORCOMBINE_ITRGB_DELTA0 = 0x03,
  GR_COLORCOMBINE_DECAL_TEXTURE = 0x04,
  GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB = 0x05,
  GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB = 0x06,
  GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0 = 0x07,
  GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA = 0x08,
  GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA = 0x09,
  GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB = 0x0A,
  GR_COLORCOMBINE_TEXTURE_ADD_ITRGB = 0x0B,
  GR_COLORCOMBINE_TEXTURE_SUB_ITRGB = 0x0C,
  GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA = 0x0D,
  GR_COLORCOMBINE_DIFF_SPEC_A = 0x0E,
  GR_COLORCOMBINE_DIFF_SPEC_B = 0x0F,
  GR_COLORCOMBINE_ONE = 0x10,
};

enum GrMPTextureCombineFnc_t : FxU32 {
  GR_MPTEXTURECOMBINE_ADD = 0x00,
  GR_MPTEXTURECOMBINE_MULTIPLY = 0x01,
  GR_MPTEXTURECOMBINE_DETAIL0 = 0x02,
  GR_MPTEXTURECOMBINE_DETAIL1 = 0x03,
  GR_MPTEXTURECOMBINE_TRILINEAR0 = 0x04,
  GR_MPTEXTURECOMBINE_TRILINEAR1 = 0x05,
  GR_MPTEXTURECOMBINE_SUBTRACT = 0x06,
};

enum GrAlphaBlendFnc_t : FxI32 {
  GR_BLEND_ZERO = 0x00,
  GR_BLEND_SRC_ALPHA = 0x01,
  GR_BLEND_SRC_COLOR = 0x02,
  GR_BLEND_DST_COLOR = GR_BLEND_SRC_COLOR,
  GR_BLEND_DST_ALPHA = 0x03 ,
  GR_BLEND_ONE = 0x04,
  GR_BLEND_ONE_MINUS_SRC_ALPHA = 0x05,
  GR_BLEND_ONE_MINUS_SRC_COLOR = 0x06,
  GR_BLEND_ONE_MINUS_DST_COLOR = GR_BLEND_ONE_MINUS_SRC_COLOR ,
  GR_BLEND_ONE_MINUS_DST_ALPHA = 0x07,
  GR_BLEND_RESERVED_8 = 0x08,
  GR_BLEND_RESERVED_9 = 0x09,
  GR_BLEND_RESERVED_A = 0x0A,
  GR_BLEND_RESERVED_B = 0x0B,
  GR_BLEND_RESERVED_C = 0x0C,
  GR_BLEND_RESERVED_D = 0x0D,
  GR_BLEND_RESERVED_E = 0x0E,
  GR_BLEND_ALPHA_SATURATE = 0x0F,
  GR_BLEND_PREFOG_COLOR = GR_BLEND_ALPHA_SATURATE,
};

enum GrBuffer_t : FxI32 {
  GR_BUFFER_NONE        = -0x01,
  GR_BUFFER_FRONTBUFFER = 0x00,
  GR_BUFFER_BACKBUFFER = 0x01,
  GR_BUFFER_AUXBUFFER = 0x02,
  GR_BUFFER_DEPTHBUFFER = 0x03,
  GR_BUFFER_ALPHABUFFER = 0x04,
  GR_BUFFER_TRIPLEBUFFER = 0x05,
  GR_BUFFER_MAXBUFFER = GR_BUFFER_TRIPLEBUFFER,
};

enum GrChromakeyMode_t : FxI32 {
  GR_CHROMAKEY_DISABLE = 0x00,
  GR_CHROMAKEY_ENABLE = 0x01,
};

enum GrChromaRangeMode_t : FxI32 {
  GR_CHROMARANGE_RGB_ALL_EXT = 0x00,
  GR_CHROMARANGE_DISABLE_EXT = 0x00,
  GR_CHROMARANGE_ENABLE_EXT = 0x01,
};

enum GrTexChromakeyMode_t : FxI32 {
  GR_TEXCHROMARANGE_RGB_ALL_EXT = 0x00,
  GR_TEXCHROMA_DISABLE_EXT = 0x00,
  GR_TEXCHROMA_ENABLE_EXT = 0x01,
};

enum GrCmpFnc_t : FxI32 {
  GR_CMP_NEVER = 0x00,
  GR_CMP_LESS = 0x01,
  GR_CMP_EQUAL = 0x02,
  GR_CMP_LEQUAL = 0x03,
  GR_CMP_GREATER = 0x04,
  GR_CMP_NOTEQUAL = 0x05,
  GR_CMP_GEQUAL = 0x06,
  GR_CMP_ALWAYS = 0x07,
};

enum GrColorFormat_t : FxI32 {
  GR_COLORFORMAT_ARGB = 0x00,
  GR_COLORFORMAT_ABGR = 0x01,
  GR_COLORFORMAT_RGBA = 0x02,
  GR_COLORFORMAT_BGRA = 0x03,
};

enum GrCullMode_t : FxI32 {
  GR_CULL_DISABLE = 0x00,
  GR_CULL_NEGATIVE = 0x01,
  GR_CULL_POSITIVE = 0x02,
};

enum GrDepthBufferMode_t : FxI32 {
  GR_DEPTHBUFFER_DISABLE = 0x00,
  GR_DEPTHBUFFER_ZBUFFER = 0x01,
  GR_DEPTHBUFFER_WBUFFER = 0x02,
  GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS = 0x03,
  GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS = 0x04,
};

enum GrDitherMode_t : FxI32 {
  GR_DITHER_DISABLE = 0x00,
  GR_DITHER_2x2 = 0x01,
  GR_DITHER_4x4 = 0x02,
};

enum GrLock_t : FxU32 {
  GR_LFB_READ_ONLY = 0x00,
  GR_LFB_IDLE = GR_LFB_READ_ONLY,
  GR_LFB_WRITE_ONLY = 0x01,
  GR_LFB_NOIDLE = 0x10,
  GR_LFB_WRITE_ONLY_EXPLICIT_EXT = 0x02
};

enum GrLfbBypassMode_t : FxI32 {
  GR_LFBBYPASS_DISABLE = 0x00,
  GR_LFBBYPASS_ENABLE = 0x01,
};

enum GrLfbWriteMode_t :  FxI32 {
  GR_LFBWRITEMODE_565 = 0x00, /* RGB:RGB */
  GR_LFBWRITEMODE_555 = 0x01, /* RGB:RGB */
  GR_LFBWRITEMODE_1555 = 0x02, /* ARGB:ARGB */
  GR_LFBWRITEMODE_RESERVED1 = 0x03,
  GR_LFBWRITEMODE_888 = 0x04, /* RGB */
  GR_LFBWRITEMODE_8888 = 0x05, /* ARGB */
  GR_LFBWRITEMODE_RESERVED2 = 0x06,
  GR_LFBWRITEMODE_RESERVED3 = 0x07,
  GR_LFBWRITEMODE_RESERVED4 = 0x08,
  GR_LFBWRITEMODE_RESERVED5 = 0x09,
  GR_LFBWRITEMODE_RESERVED6 = 0x0A,
  GR_LFBWRITEMODE_RESERVED7 = 0x0B,
  GR_LFBWRITEMODE_565_DEPTH = 0x0C, /* RGB:DEPTH */
  GR_LFBWRITEMODE_555_DEPTH = 0x0D, /* RGB:DEPTH */
  GR_LFBWRITEMODE_1555_DEPTH = 0x0E, /* ARGB:DEPTH */
  GR_LFBWRITEMODE_ZA16 = 0x0F, /* DEPTH:DEPTH */
  GR_LFBWRITEMODE_ANY = 0xFF,
};

enum GrOriginLocation_t : FxI32 {
  GR_ORIGIN_UPPER_LEFT = 0x00,
  GR_ORIGIN_LOWER_LEFT = 0x01,
  GR_ORIGIN_ANY = 0xFF,
};

enum GrPassthruMode_t : FxI32 {
  GR_PASSTHRU_SHOW_VGA = 0x0,
  GR_PASSTHRU_SHOW_SST1 = 0x1,
};

enum GrMipMapMode_t : FxI32 {
  GR_MIPMAP_DISABLE = 0x00,
  GR_MIPMAP_NEAREST = 0x01,
  GR_MIPMAP_NEAREST_DITHER = 0x02,
};

enum GrScreenRefresh_t : FxU32 {
  GR_REFRESH_60Hz = 0x00,
  GR_REFRESH_70Hz = 0x01,
  GR_REFRESH_72Hz = 0x02,
  GR_REFRESH_75Hz = 0x03,
  GR_REFRESH_80Hz = 0x04,
  GR_REFRESH_90Hz = 0x05,
  GR_REFRESH_100Hz = 0x06,
  GR_REFRESH_85Hz = 0x07,
  GR_REFRESH_120Hz = 0x08,
  GR_REFRESH_MIN = GR_REFRESH_60Hz,
  GR_REFRESH_MAX = GR_REFRESH_120Hz,
  GR_REFRESH_EXTENDED = 0x7FFF7FFF,
  GR_REFRESH_NONE = 0xFF,
};

enum GrScreenResolution_t : FxU32 {
  GR_RESOLUTION_320x200 = 0x00,
  GR_RESOLUTION_320x240 = 0x01,
  GR_RESOLUTION_400x256 = 0x02,
  GR_RESOLUTION_512x384 = 0x03,
  GR_RESOLUTION_640x200 = 0x04,
  GR_RESOLUTION_640x350 = 0x05,
  GR_RESOLUTION_640x400 = 0x06,
  GR_RESOLUTION_640x480 = 0x07,
  GR_RESOLUTION_800x600 = 0x08,
  GR_RESOLUTION_960x720 = 0x09,
  GR_RESOLUTION_856x480 = 0x0A,
  GR_RESOLUTION_512x256 = 0x0B,
  GR_RESOLUTION_1024x768 = 0x0C,
  GR_RESOLUTION_1280x1024 = 0x0D,
  GR_RESOLUTION_1600x1200 = 0x0E,
  GR_RESOLUTION_400x300 = 0x0F,
  GR_RESOLUTION_1152x864 = 0x10,
  GR_RESOLUTION_1280x960 = 0x11,
  GR_RESOLUTION_1600x1024 = 0x12,
  GR_RESOLUTION_1792x1344 = 0x13,
  GR_RESOLUTION_1856x1392 = 0x14,
  GR_RESOLUTION_1920x1440 = 0x15,
  GR_RESOLUTION_2048x1536 = 0x16,
  GR_RESOLUTION_2048x2048 = 0x17,
  GR_RESOLUTION_NONE = 0xFF,
  GR_RESOLUTION_MIN = GR_RESOLUTION_320x200,
  GR_RESOLUTION_MAX = GR_RESOLUTION_2048x2048,
  GR_RESOLUTION_EXTENDED = 0x7FFF7FFF,
};

enum GrHint_t : FxU32 {
  GR_HINT_STWHINT = 0x00,
  GR_HINTTYPE_MIN = GR_HINT_STWHINT,
  GR_HINT_FIFOCHECKHINT = 0x01,
  GR_HINT_FPUPRECISION = 0x02,
  GR_HINT_ALLOW_MIPMAP_DITHER = 0x03,
  GR_HINT_LFB_WRITE = 0x04,
  GR_HINT_LFB_PROTECT = 0x05,
  GR_HINT_LFB_RESET = 0x06,
  GR_HINTTYPE_MAX = GR_HINT_LFB_RESET,
};

enum GrSTWHint_t : FxU32 {
  GR_STWHINT_W_DIFF_FBI = FXBIT(0),
  GR_STWHINT_W_DIFF_TMU0 = FXBIT(1),
  GR_STWHINT_ST_DIFF_TMU0 = FXBIT(2),
  GR_STWHINT_W_DIFF_TMU1 = FXBIT(3),
  GR_STWHINT_ST_DIFF_TMU1 = FXBIT(4),
  GR_STWHINT_W_DIFF_TMU2 = FXBIT(5),
  GR_STWHINT_ST_DIFF_TMU2 = FXBIT(6),
};

enum GrSmoothingMode_t : FxI32 {
  GR_SMOOTHING_DISABLE = 0x00,
  GR_SMOOTHING_ENABLE = 0x01,
};

enum GrTextureClampMode_t : FxI32 {
  GR_TEXTURECLAMP_WRAP = 0x00,
  GR_TEXTURECLAMP_CLAMP = 0x01,
  GR_TEXTURECLAMP_MIRROR_EXT = 0x02,
};

enum GrTextureCombineFnc_t : FxI32 {
  GR_TEXTURECOMBINE_ZERO = 0x00,
  GR_TEXTURECOMBINE_DECAL = 0x01,
  GR_TEXTURECOMBINE_OTHER = 0x02,
  GR_TEXTURECOMBINE_ADD = 0x03,
  GR_TEXTURECOMBINE_MULTIPLY = 0x04,
  GR_TEXTURECOMBINE_SUBTRACT = 0x05,
  GR_TEXTURECOMBINE_DETAIL = 0x06,
  GR_TEXTURECOMBINE_DETAIL_OTHER = 0x07,
  GR_TEXTURECOMBINE_TRILINEAR_ODD = 0x08,
  GR_TEXTURECOMBINE_TRILINEAR_EVEN = 0x09,
  GR_TEXTURECOMBINE_ONE = 0x0A,
};

enum GrTextureFilterMode_t : FxI32 {
  GR_TEXTUREFILTER_POINT_SAMPLED = 0x0,
  GR_TEXTUREFILTER_BILINEAR = 0x1,
};

enum GrTextureFormat_t : FxI32 {
  GR_TEXFMT_8BIT = 0x00,
  GR_TEXFMT_RGB_332 = GR_TEXFMT_8BIT,
  GR_TEXFMT_YIQ_422 = 0x01,
  GR_TEXFMT_ALPHA_8 = 0x02,
  GR_TEXFMT_INTENSITY_8 = 0x03,
  GR_TEXFMT_ALPHA_INTENSITY_44 = 0x04,
  GR_TEXFMT_P_8 = 0x05,
  GR_TEXFMT_RSVD0 = 0x06,
  GR_TEXFMT_P_8_6666 = GR_TEXFMT_RSVD0,
  GR_TEXFMT_P_8_6666_EXT = GR_TEXFMT_RSVD0,
  GR_TEXFMT_RSVD1 = 0x07,
  GR_TEXFMT_16BIT = 0x08,
  GR_TEXFMT_ARGB_8332 = GR_TEXFMT_16BIT,
  GR_TEXFMT_AYIQ_8422 = 0x09,
  GR_TEXFMT_RGB_565 = 0x0A,
  GR_TEXFMT_ARGB_1555 = 0x0B,
  GR_TEXFMT_ARGB_4444 = 0x0C,
  GR_TEXFMT_ALPHA_INTENSITY_88 = 0x0D,
  GR_TEXFMT_AP_88 = 0x0E,
  GR_TEXFMT_RSVD2 = 0x0F,
  GR_TEXFMT_RSVD4 = GR_TEXFMT_RSVD2,
  // Napalm
  GR_TEXFMT_ARGB_CMP_FXT1 = 0x11,
  GR_TEXFMT_ARGB_8888 = 0x12,
  GR_TEXFMT_YUYV_422 = 0x13,
  GR_TEXFMT_UYVY_422 = 0x14,
  GR_TEXFMT_AYUV_444 = 0x15,
  GR_TEXFMT_ARGB_CMP_DXT1 = 0x16,
  GR_TEXFMT_ARGB_CMP_DXT2 = 0x17,
  GR_TEXFMT_ARGB_CMP_DXT3 = 0x18,
  GR_TEXFMT_ARGB_CMP_DXT4 = 0x19,
  GR_TEXFMT_ARGB_CMP_DXT5 = 0x1A,
  GR_TEXFMT_RGB_888 = 0xFF,

};

enum GrTexTable_t : FxU32 {
  GR_TEXTABLE_NCC0 = 0x00,
  GR_TEXTABLE_NCC1 = 0x01,
  GR_TEXTABLE_PALETTE = 0x02,
  GR_TEXTABLE_PALETTE_6666_EXT = 0x03,
};

enum GrNCCTable_t : FxU32 {
  GR_NCCTABLE_NCC0 = 0x00,
  GR_NCCTABLE_NCC1 = 0x01,
};

enum GrTexBaseRange_t : FxU32 {
  GR_TEXBASE_256 = 0x03,
  GR_TEXBASE_128 = 0x02,
  GR_TEXBASE_64 = 0x01,
  GR_TEXBASE_32_TO_1 = 0x00,
};

enum GrEnableMode_t : FxU32 {
  GR_MODE_DISABLE = 0x00,
  GR_AA_ORDERED = 0x01,
  GR_MODE_ENABLE = GR_AA_ORDERED,
  GR_ALLOW_MIPMAP_DITHER = 0x02,
  GR_PASSTHRU = 0x03,
  GR_SHAMELESS_PLUG = 0x04,
  GR_VIDEO_SMOOTHING = 0x05,
};

enum GrLfbSrcFmt_t : FxU32 {
  GR_LFB_SRC_FMT_565 = 0x00,
  GR_LFB_SRC_FMT_555 = 0x01,
  GR_LFB_SRC_FMT_1555 = 0x02,
  GR_LFB_SRC_FMT_888 = 0x04,
  GR_LFB_SRC_FMT_8888 = 0x05,
  GR_LFB_SRC_FMT_565_DEPTH = 0x0C,
  GR_LFB_SRC_FMT_555_DEPTH = 0x0D,
  GR_LFB_SRC_FMT_1555_DEPTH = 0x0E,
  GR_LFB_SRC_FMT_ZA16 = 0x0F,
  GR_LFB_SRC_FMT_RLE16 = 0x80,
};

enum GrSstType : FxI32 {
  GR_SSTTYPE_Voodoo = 0x00,
  GR_SSTTYPE_SST96 = 0x01,  //Rush
  GR_SSTTYPE_AT3D = 0x02,
  GR_SSTTYPE_Voodoo2 = 0x03,
  GR_SSTTYPE_Banshee = 0x04,
  GR_SSTTYPE_Voodoo3 = 0x05,
  GR_SSTTYPE_Voodoo4 = 0x06,
  GR_SSTTYPE_Voodoo5 = 0x07,
};

enum GrSstRegister : FxU32 {
   SSTR_STATUS,
   SSTR_RESERVED0,
   SSTR_VAX,
   SSTR_VAY,
   SSTR_VBX,
   SSTR_VBY,
   SSTR_VCX,
   SSTR_VCY,
#ifdef GLIDE_USE_ALT_REGMAP
   SSTR_R,
   SSTR_DRDX,
   SSTR_DRDY,

   SSTR_G,
   SSTR_DGDX,
   SSTR_DGDY,

   SSTR_B,
   SSTR_DBDX,
   SSTR_DBDY,

   SSTR_Z,
   SSTR_DZDX,
   SSTR_DZDY,

   SSTR_A,
   SSTR_DADX,
   SSTR_DADY,

   SSTR_S,
   SSTR_DSDX,
   SSTR_DSDY,

   SSTR_T,
   SSTR_DTDX,
   SSTR_DTDY,

   SSTR_W,
   SSTR_DWDX,
   SSTR_DWDY,
#else
   SSTR_R,
   SSTR_G,
   SSTR_B,
   SSTR_Z,
   SSTR_A,
   SSTR_S,
   SSTR_T,
   SSTR_W,

   SSTR_DRDX,
   SSTR_DGDX,
   SSTR_DBDX,
   SSTR_DZDX,
   SSTR_DADX,
   SSTR_DSDX,
   SSTR_DTDX,
   SSTR_DWDX,

   SSTR_DRDY,
   SSTR_DGDY,
   SSTR_DBDY,
   SSTR_DZDY,
   SSTR_DADY,
   SSTR_DSDY,
   SSTR_DTDY,
   SSTR_DWDY,
#endif
   SSTR_TRIANGLECMD,
   SSTR_RESERVED1,

   SSTR_FVAX,
   SSTR_FVAY,
   SSTR_FVBX,
   SSTR_FVBY,
   SSTR_FVCX,
   SSTR_FVCY,
#ifdef GLIDE_USE_ALT_REGMAP
   SSTR_FR,
   SSTR_FDRDX,
   SSTR_FDRDY,

   SSTR_FG,
   SSTR_FDGDX,
   SSTR_FDGDY,

   SSTR_FB,
   SSTR_FDBDX,
   SSTR_FDBDY,

   SSTR_FZ,
   SSTR_FDZDX,
   SSTR_FDZDY,

   SSTR_FA,
   SSTR_FDADX,
   SSTR_FDADY,

   SSTR_FS,
   SSTR_FDSDX,
   SSTR_FDSDY,

   SSTR_FT,
   SSTR_FDTDX,
   SSTR_FDTDY,

   SSTR_FW,
   SSTR_FDWDX,
   SSTR_FDWDY,
#else
   SSTR_FR,
   SSTR_FG,
   SSTR_FB,
   SSTR_FZ,
   SSTR_FA,
   SSTR_FS,
   SSTR_FT,
   SSTR_FW,

   SSTR_FDRDX,
   SSTR_FDGDX,
   SSTR_FDBDX,
   SSTR_FDZDX,
   SSTR_FDADX,
   SSTR_FDSDX,
   SSTR_FDTDX,
   SSTR_FDWDX,

   SSTR_FDRDY,
   SSTR_FDGDY,
   SSTR_FDBDY,
   SSTR_FDZDY,
   SSTR_FDADY,
   SSTR_FDSDY,
   SSTR_FDTDY,
   SSTR_FDWDY,
#endif
   SSTR_FTRIANGLECMD,
   SSTR_FBZCOLORPATH,
   SSTR_FOGMODE,
   SSTR_ALPHAMODE,
   SSTR_FBZMODE,
   SSTR_LFBMODE,
   SSTR_CLIPLEFTRIGHT,
   SSTR_CLIPBOTTOMTOP,

   SSTR_NOPCMD,
   SSTR_FASTFILLCMD,
   SSTR_SWAPBUFFERCMD,
   SSTR_FOGCOLOR,
   SSTR_ZACOLOR,
   SSTR_CHROMAKEY,
   SSTR_RESERVED2,
   SSTR_RESERVED3,

   SSTR_STIPPLE,
   SSTR_C0,
   SSTR_C1,

   SSTR_FBIPIXELSIN,
   SSTR_FBICHROMAFAIL,
   SSTR_FBIZFUNCFAIL,
   SSTR_FBIAFUNCFAIL,
   SSTR_FBIPIXELSOUT,

   SSTR_FOGTABLE,
   SSTR_RESERVED8 = SSTR_FOGTABLE + 32,

   SSTR_FBIINIT4 = SSTR_RESERVED8 + 8,
   SSTR_VRETRACE,
   SSTR_BACKPORCH,
   SSTR_VIDEODIMENSIONS,
   SSTR_FBIINIT0,
   SSTR_FBIINIT1,
   SSTR_FBIINIT2,
   SSTR_FBIINIT3,

   SSTR_HSYNC,
   SSTR_VSYNC,
   SSTR_CLUTDATA,
   SSTR_DACDATA,
   SSTR_MAX_RGB_DELTA,
   SSTR_RESERVED51,

   SSTR_TEXTUREMODE = SSTR_RESERVED51 + 51,
   SSTR_TLOD,
   SSTR_TDETAIL,
   SSTR_TEXBASEADDR,
   SSTR_TEXBASEADDR1,
   SSTR_TEXBASEADDR2,
   SSTR_TEXBASEADDR38,
   SSTR_TEXINIT0,
   SSTR_TEXINIT1,

   SSTR_NCCTABLE0,
   SSTR_NCCTABLE1 = SSTR_NCCTABLE0 + 12,
   SSTR_END_OF_REGISTER_SET
};

enum MipMapLevelMask_t : FxU32 {
  GR_MIPMAPLEVELMASK_NONE = 0,
  GR_MIPMAPLEVELMASK_EVEN = FXBIT(0),
  GR_MIPMAPLEVELMASK_ODD = FXBIT(1),
  GR_MIPMAPLEVELMASK_BOTH = (GR_MIPMAPLEVELMASK_EVEN | GR_MIPMAPLEVELMASK_ODD)
};

typedef struct {
    FxI32              size;
    void               *lfbPtr;
    FxU32              strideInBytes;
    GrLfbWriteMode_t   writeMode;
    GrOriginLocation_t origin;
} GrLfbInfo_t;

typedef struct {
    GrScreenResolution_t resolution;
    FxU32 xres;
    FxU32 yres;
} ResEntry;

typedef struct GrTMUConfig_St {
  FxI32 tmuRev;                /* Rev of Texelfx chip */
  FxI32 tmuRam;                /* 1, 2, or 4 MB */
} GrTMUConfig_t;

typedef struct GrVoodooConfig_St {
  FxI32  fbRam;                         /* 1, 2, or 4 MB */
  FxI32  fbiRev;                        /* Rev of Pixelfx chip */
  FxI32  nTexelfx;                      /* How many texelFX chips are there? */
  FxBool sliDetect;                     /* Is it a scan-line interleaved board? */
  GrTMUConfig_t tmuConfig[GLIDE_NUM_TMU];   /* Configuration of the Texelfx chips */
} GrVoodooConfig_t;

typedef struct GrSst96Config_St {
  FxI32 fbRam;                  /* How much? */
  FxI32 nTexelfx;
  GrTMUConfig_t tmuConfig;
} GrSst96Config_t;

typedef GrVoodooConfig_t GrVoodoo2Config_t;

typedef struct GrAT3DConfig_St {
  int   rev;
} GrAT3DConfig_t;

typedef struct {
  int num_sst;                  /* # of HW units in the system */
  struct {
    GrSstType type;             /* Which hardware is it? */
    union SstBoard_u {
      GrVoodooConfig_t  VoodooConfig;
      GrSst96Config_t   SST96Config;
      GrAT3DConfig_t    AT3DConfig;
      GrVoodoo2Config_t Voodoo2Config;
    } sstBoard;
  } SSTs[MAX_NUM_SST];          /* configuration for each board */
} GrHwConfiguration;

typedef struct GrSstPerfStats_s {
  FxU32 pixelsIn;   /* # of pixels processed (minus buffer clears) */
  FxU32 chromaFail; /* # of pixels not drawn due to chroma key */
  FxU32 zFuncFail;  /* # of pixels not drawn due to Z comparison */
  FxU32 aFuncFail;  /* # of pixels not drawn due to alpha comparison */
  FxU32 pixelsOut;  /* # of pixels drawn (including buffer clears) */
} GrSstPerfStats_t;

typedef struct {
  FxU8  yRGB[16];
  FxI16 iRGB[4][3];
  FxI16 qRGB[4][3];
  FxU32 packed_data[12];
} GuNccTable;

typedef struct {
  FxU32 data[256];
} GuTexPalette;

typedef union {
  GuNccTable   nccTable;
  GuTexPalette palette;
} GuTexTable;

typedef struct {
  FxU32 hSyncOn;
  FxU32 hSyncOff;
  FxU32 vSyncOn;
  FxU32 vSyncOff;
  FxU32 hBackPorch;
  FxU32 vBackPorch;
  FxU32 xDimension;
  FxU32 yDimension;
  FxU32 memOffset;
  FxU32 memFifoEntries_1MB;
  FxU32 memFifoEntries_2MB;
  FxU32 memFifoEntries_4MB;
  FxU32 tilesInX_Over2;
  FxU32 vFifoThreshold;
  FxBool video16BPPIsOK;
  FxBool video24BPPIsOK;
  float clkFreq16bpp;
  float clkFreq24bpp;
} FxVideoTimingInfo;

enum PciMemType : FxI32 {
  PciMemTypeUncacheable = 0x00,
  PciMemTypeWriteCombining = 0x01,
  PciMemTypeWriteThrough = 0x04,
  PciMemTypeWriteProtected = 0x05,
  PciMemTypeWriteback = 0x06,
};

enum PciIOFlag : FxI32 {
  READ_ONLY,
  WRITE_ONLY,
  READ_WRITE
};

typedef struct {
    FxU32              regAddress;
    FxU32              sizeInBytes;
    PciIOFlag          rwFlag;
} PciRegister;
